### ISSUE TITLE
When I was using the from Docs2KG. Parser. pdf. pdf2metadata import get_metadata_for files import method, I had already reported an error. 

### ISSUE THREAD

**Issue by tyronemaxi** [AI4WA/Docs2KG#98]
**Describe the bug**
When I was using the `from Docs2KG.parser.pdf.pdf2metadata import get_metadata_for_files` files import method, I had already reported an error. 

**To Reproduce**
1. from Docs2KG.parser.pdf.pdf2metadata import get_metadata_for_files
2. reprot a error which is : Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Expected behavior**
i use the usage from: https://docs2kg.ai4wa.com/Tutorial/2.DualPathProcessing/#pdf-files
but it cannot work...

**Screenshots**
<img width="1035" alt="image" src="https://github.com/AI4WA/Docs2KG/assets/86507360/2482134f-6fd0-4cc6-8793-ec5ddc6f40a9">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PascalSun** [comment]
the exit code 139 should not be the detailed error message. 

So how you install the package? use pip install?

**Comment by PascalSun** [comment]
After you install the `pip install Docs2KG`, have you try

python3

```
>import Docs2KG
```

to verify the installation successful?

**Comment by tyronemaxi** [comment]
this is my local enviroment:
(docs2KG_test) *********$ pip list | grep Docs2KG
Docs2KG               0.2.3
(docs2KG_test) ********* (main*) $ python3 --version      
Python 3.10.13
(docs2KG_test)********* (main*) $ python3          
Python 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Docs2KG
>>> from Docs2KG.parser.pdf.pdf2metadata import get_metadata_for_files
[1]    70706 segmentation fault  python3

it cannot work correctly....
------
I am very interested in this project, and I will try other modules
i find some issues in stackoverflow: https://stackoverflow.com/questions/66337481/calling-python3-causes-a-segmentation-fault, i guess that may be the c or c++ module in base, which need gdb to debug。

**Comment by tyronemaxi** [comment]
Thanks for your reply

**Comment by PascalSun** [comment]
> this is my local enviroment: (docs2KG_test) **_$ pip list | grep Docs2KG Docs2KG 0.2.3 (docs2KG_test) ********* (main_) $ python3 --version Python 3.10.13 (docs2KG_test)*** (main*) $ python3 Python 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ] on darwin Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import Docs2KG
> > > > from Docs2KG.parser.pdf.pdf2metadata import get_metadata_for_files
> > > > [1]    70706 segmentation fault  python3
> 
> ## it cannot work correctly....
> I am very interested in this project, and I will try other modules i find some issues in stackoverflow: https://stackoverflow.com/questions/66337481/calling-python3-causes-a-segmentation-fault, i guess that may be the c or c++ module in base, which need gdb to debug。

70706 segmentation fault python3

Your python venv seems have some problem..

this normally happen when you do not have enough memory.
